### PR TITLE
changed accuracy in data/org.mate.calc.gschema.xml.in to 15

### PR DESCRIPTION
**Pull request by tylnesh**
Several issues were opened because the accuracy was set too low. Changed it to 15, but will provide a slider to set the accuracy in the settings later.

### CODE REVIEW

**Comment by lukefromdc** [comment]
I got no effect from this change running on Debian Unstable, not sure if I did something wrong or what. Recompiling schemas didn't help

**Comment by tylnesh** [comment]
Silly question (i'm new at this), do you, by any chance have had your mate-calc installed from repositories before doing  the ./autogen -> make -> make install ?

**Comment by lukefromdc** [comment]
My debian packages are installed from local builds, and the build options I use in testing are the same as I use when building packages, so everything gets installed cleanly to the same places

**Comment by lukefromdc** [comment]
Also, I used "make uninstall" in one test to strip out all of the old build before installing the new build, got same results

**Comment by tylnesh** [comment]
So strange. I spinned up a new Ubuntu Mate VM, cloned it, compiled it and it works as it should.

**Comment by lukefromdc** [comment]
Asking others to try this, I have no idea what's going on

**Comment by raveit65** [comment]
I just tested it with
```
From 177792f4442de01ff45ebe2ac1964d9b4328c1dc Mon Sep 17 00:00:00 2001
From: tylnesh <kohutek.michal@gmail.com>
Date: Wed, 7 Feb 2018 09:59:10 +0100
Subject: [PATCH] changed accuracy range to 15

---
 data/org.mate.calc.gschema.xml.in | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/data/org.mate.calc.gschema.xml.in b/data/org.mate.calc.gschema.xml.in
index e0b1792..37295c1 100644
--- a/data/org.mate.calc.gschema.xml.in
+++ b/data/org.mate.calc.gschema.xml.in
@@ -21,7 +21,7 @@
   <schema path="/org/mate/calc/" id="org.mate.calc" gettext-domain="mate-calc">
     <key type="i" name="accuracy">
       <default>9</default>
-      <range min="0" max="9"/>
+      <range min="0" max="15"/>
       <summary>Accuracy value</summary>
       <description>The number of digits displayed after the numeric point</description>
     </key>
-- 
2.13.6
```
I can confirm that the gsettings key itself is working, but the spinbutton in preferences shows always 9 as max range.

**Comment by vkareh** [comment]
Created a new pull request fixing this: #86

**Pull request closed without merging**
