### PR TITLE
UI: replace all deprecated elements

### PR DESCRIPTION
**Pull request by raveit65**
Please test.

### CODE REVIEW

**Comment by raveit65** [comment]
@sc0w 
Oh i didn't know that. Of course i agree with adding commits here :)

**Comment by raveit65** [comment]
Hmm, last commit breaks the dialogs in eg. financial mode.
I got this warning
```
[rave@mother ~]$ mate-calc

** (mate-calc:6710): WARNING **: 09:57:48.701: Error loading button UI: /usr/share/mate-calc/buttons-financial.ui:37:41 Object with ID image1 not found
```
and 'cancel buttons' doesn't have a icon any more.
Also, it seems that the buttons lost functions. Try to use the rate dialog.
Before:
mate-calc-rate-dialog
After:
mate-calc-rate-dialog-broken

**Comment by sc0w** [comment]
I did some changes

@vkareh @lukefromdc @raveit65 please test again

**Comment by lukefromdc** [comment]
The cancel button is back, but somewhere in this we've picked up some out of position combo box menus. Image coming

**Comment by lukefromdc** [comment]
mate-calc-comboboxes_6-2-2018

This happened sporadically, not all the time so when it happened I had to use a camera rather than a screenshot to capture it

**Comment by raveit65** [comment]
I can reproduce this with master too, so it's not related to UI changes here.
You need to open the comboboxes in financial mode first , than try to open the comboboxes in advanced mode. A little video which demonstrate it. (5.7 MB)
https://www.dropbox.com/s/jf8axx21u4xlhi3/mate-calc.ogv.tar.xz?dl=0
Can you please file another report for this new issue?

**Comment by lukefromdc** [comment]
I too just confirmed this with master, so this PR should be OK. New issue reported at
https://github.com/mate-desktop/mate-calc/issues/56

**Comment by raveit65** [comment]
Icons and function for buttons are back with latest change.

**Pull request merged**
