### PR TITLE
Migrate from intltools into gettext

### PR DESCRIPTION
**Pull request by yetist**

### CODE REVIEW

**Comment by rbuj** [comment]
xgettext doesn't recognize ui and xml files, messages are lost:
```shell
$ ./autogen.sh --prefix=/usr && ./makepot
...
/usr/bin/xgettext: warning: file 'src/buttons-advanced.ui' extension 'ui' is unknown; will try C
/usr/bin/xgettext: warning: file 'src/buttons-basic.ui' extension 'ui' is unknown; will try C
/usr/bin/xgettext: warning: file 'src/buttons-financial.ui' extension 'ui' is unknown; will try C
src/buttons-financial.ui:1446: warning: unterminated character constant
src/buttons-financial.ui:1631: warning: unterminated character constant
/usr/bin/xgettext: warning: file 'src/buttons-programming.ui' extension 'ui' is unknown; will try C
/usr/bin/xgettext: warning: file 'src/preferences.ui' extension 'ui' is unknown; will try C
/usr/bin/xgettext: warning: file 'data/mate-calc.appdata.xml.in' extension 'xml' is unknown; will try C
data/mate-calc.appdata.xml.in:18: warning: unterminated character constant
/usr/bin/xgettext: warning: file 'data/org.mate.calc.gschema.xml' extension 'xml' is unknown; will try C
...
$ git diff --stat mate-calc.pot
...
 1 file changed, 494 insertions(+), 809 deletions(-)
```

**Comment by raveit65** [comment]
@rbuj 
Where/How do you get this warnings?
```
[rave@mother mate-calc-dist]$ ./autogen.sh --prefix=/usr && ./makepot
/usr/bin/mate-autogen
/usr/bin/yelp-build

<cut>

config.status: executing po-directories commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
Now type `make' to compile mate-calc
make: Entering directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-calc-dist/po'
make mate-calc.pot-update
make[1]: Entering directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-calc-dist/po'
sed -e '/^#/d' remove-potcdate.sin > t-remove-potcdate.sed
mv t-remove-potcdate.sed remove-potcdate.sed
package_gnu=""; \
test -n "$package_gnu" || { \
  if { if (LC_ALL=C find --version) 2>/dev/null | grep GNU >/dev/null; then \
	 LC_ALL=C find -L .. -maxdepth 1 -type f \
		       -size -10000000c -exec grep 'GNU mate-calc' \
		       /dev/null '{}' ';' 2>/dev/null; \
       else \
	 LC_ALL=C grep 'GNU mate-calc' ../* 2>/dev/null; \
       fi; \
     } | grep -v 'libtool:' >/dev/null; then \
     package_gnu=yes; \
   else \
     package_gnu=no; \
   fi; \
}; \
if test "$package_gnu" = "yes"; then \
  package_prefix='GNU '; \
else \
  package_prefix=''; \
fi; \
if test -n '' || test 'http://mate-desktop.org' = '@'PACKAGE_BUGREPORT'@'; then \
  msgid_bugs_address=''; \
else \
  msgid_bugs_address='http://mate-desktop.org'; \
fi; \
case `/usr/bin/xgettext --version | sed 1q | sed -e 's,^[^0-9]*,,'` in \
  '' | 0.[0-9] | 0.[0-9].* | 0.1[0-5] | 0.1[0-5].* | 0.16 | 0.16.[0-1]*) \
    /usr/bin/xgettext --default-domain=mate-calc --directory=.. \
      --add-comments=TRANSLATORS: --from-code=UTF-8 --keyword=_ --keyword=N_ --keyword=C_:1c,2 --keyword=NC_:1c,2 --keyword=g_dngettext:2,3 --add-comments  \
      --files-from=./POTFILES.in \
      --copyright-holder='MATE Desktop Environment team' \
      --msgid-bugs-address="$msgid_bugs_address" \
    ;; \
  *) \
    /usr/bin/xgettext --default-domain=mate-calc --directory=.. \
      --add-comments=TRANSLATORS: --from-code=UTF-8 --keyword=_ --keyword=N_ --keyword=C_:1c,2 --keyword=NC_:1c,2 --keyword=g_dngettext:2,3 --add-comments  \
      --files-from=./POTFILES.in \
      --copyright-holder='MATE Desktop Environment team' \
      --package-name="${package_prefix}mate-calc" \
      --package-version='1.23.0' \
      --msgid-bugs-address="$msgid_bugs_address" \
    ;; \
esac
test ! -f mate-calc.po || { \
  if test -f ./mate-calc.pot-header; then \
    sed -e '1,/^#$/d' < mate-calc.po > mate-calc.1po && \
    cat ./mate-calc.pot-header mate-calc.1po > mate-calc.po; \
    rm -f mate-calc.1po; \
  fi; \
  if test -f ./mate-calc.pot; then \
    sed -f remove-potcdate.sed < ./mate-calc.pot > mate-calc.1po && \
    sed -f remove-potcdate.sed < mate-calc.po > mate-calc.2po && \
    if cmp mate-calc.1po mate-calc.2po >/dev/null 2>&1; then \
      rm -f mate-calc.1po mate-calc.2po mate-calc.po; \
    else \
      rm -f mate-calc.1po mate-calc.2po ./mate-calc.pot && \
      mv mate-calc.po ./mate-calc.pot; \
    fi; \
  else \
    mv mate-calc.po ./mate-calc.pot; \
  fi; \
}
make[1]: Leaving directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-calc-dist/po'
make: Leaving directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-calc-dist/po'
make: Entering directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-calc-dist/help'
  GEN      mate-calc.pot
make: Leaving directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-calc-dist/help'


[rave@mother mate-calc-dist]$ git diff --stat mate-calc.pot
 mate-calc.pot | 1155 ++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------
 1 file changed, 697 insertions(+), 458 deletions(-)
```

**Comment by lukefromdc** [comment]
What of the usual issue of problems with distcheck tarballs with this and without Meson?

**Comment by rbuj** [comment]
```shell
$ cat /etc/redhat-release 
Fedora release 30 (Thirty)
$ rpm -qf /usr/bin/xgettext
gettext-0.19.8.1-18.fc30.x86_64
```
```shell
Now type `make' to compile mate-calc
make: Entering directory '/home/robert/devel/mate-calc/po'
make mate-calc.pot-update
make[1]: Entering directory '/home/robert/devel/mate-calc/po'
sed -e '/^#/d' remove-potcdate.sin > t-remove-potcdate.sed
mv t-remove-potcdate.sed remove-potcdate.sed
package_gnu=""; \
test -n "$package_gnu" || { \
  if { if (LC_ALL=C find --version) 2>/dev/null | grep GNU >/dev/null; then \
	 LC_ALL=C find -L .. -maxdepth 1 -type f \
		       -size -10000000c -exec grep 'GNU mate-calc' \
		       /dev/null '{}' ';' 2>/dev/null; \
       else \
	 LC_ALL=C grep 'GNU mate-calc' ../* 2>/dev/null; \
       fi; \
     } | grep -v 'libtool:' >/dev/null; then \
     package_gnu=yes; \
   else \
     package_gnu=no; \
   fi; \
}; \
if test "$package_gnu" = "yes"; then \
  package_prefix='GNU '; \
else \
  package_prefix=''; \
fi; \
if test -n '' || test 'http://mate-desktop.org' = '@'PACKAGE_BUGREPORT'@'; then \
  msgid_bugs_address=''; \
else \
  msgid_bugs_address='http://mate-desktop.org'; \
fi; \
case `/usr/bin/xgettext --version | sed 1q | sed -e 's,^[^0-9]*,,'` in \
  '' | 0.[0-9] | 0.[0-9].* | 0.1[0-5] | 0.1[0-5].* | 0.16 | 0.16.[0-1]*) \
    /usr/bin/xgettext --default-domain=mate-calc --directory=.. \
      --add-comments=TRANSLATORS: --from-code=UTF-8 --keyword=_ --keyword=N_ --keyword=C_:1c,2 --keyword=NC_:1c,2 --keyword=g_dngettext:2,3 --add-comments  \
      --files-from=./POTFILES.in \
      --copyright-holder='MATE Desktop Environment team' \
      --msgid-bugs-address="$msgid_bugs_address" \
    ;; \
  *) \
    /usr/bin/xgettext --default-domain=mate-calc --directory=.. \
      --add-comments=TRANSLATORS: --from-code=UTF-8 --keyword=_ --keyword=N_ --keyword=C_:1c,2 --keyword=NC_:1c,2 --keyword=g_dngettext:2,3 --add-comments  \
      --files-from=./POTFILES.in \
      --copyright-holder='MATE Desktop Environment team' \
      --package-name="${package_prefix}mate-calc" \
      --package-version='1.23.0' \
      --msgid-bugs-address="$msgid_bugs_address" \
    ;; \
esac
/usr/bin/xgettext: warning: file 'src/buttons-advanced.ui' extension 'ui' is unknown; will try C
/usr/bin/xgettext: warning: file 'src/buttons-basic.ui' extension 'ui' is unknown; will try C
/usr/bin/xgettext: warning: file 'src/buttons-financial.ui' extension 'ui' is unknown; will try C
src/buttons-financial.ui:1446: warning: unterminated character constant
src/buttons-financial.ui:1631: warning: unterminated character constant
/usr/bin/xgettext: warning: file 'src/buttons-programming.ui' extension 'ui' is unknown; will try C
/usr/bin/xgettext: warning: file 'src/preferences.ui' extension 'ui' is unknown; will try C
/usr/bin/xgettext: warning: file 'data/mate-calc.appdata.xml.in' extension 'xml' is unknown; will try C
data/mate-calc.appdata.xml.in:18: warning: unterminated character constant
/usr/bin/xgettext: warning: file 'data/org.mate.calc.gschema.xml' extension 'xml' is unknown; will try C
test ! -f mate-calc.po || { \
  if test -f ./mate-calc.pot-header; then \
    sed -e '1,/^#$/d' < mate-calc.po > mate-calc.1po && \
    cat ./mate-calc.pot-header mate-calc.1po > mate-calc.po; \
    rm -f mate-calc.1po; \
  fi; \
  if test -f ./mate-calc.pot; then \
    sed -f remove-potcdate.sed < ./mate-calc.pot > mate-calc.1po && \
    sed -f remove-potcdate.sed < mate-calc.po > mate-calc.2po && \
    if cmp mate-calc.1po mate-calc.2po >/dev/null 2>&1; then \
      rm -f mate-calc.1po mate-calc.2po mate-calc.po; \
    else \
      rm -f mate-calc.1po mate-calc.2po ./mate-calc.pot && \
      mv mate-calc.po ./mate-calc.pot; \
    fi; \
  else \
    mv mate-calc.po ./mate-calc.pot; \
  fi; \
}
make[1]: Leaving directory '/home/robert/devel/mate-calc/po'
make: Leaving directory '/home/robert/devel/mate-calc/po'
make: Entering directory '/home/robert/devel/mate-calc/help'
  GEN      mate-calc.pot
make: Leaving directory '/home/robert/devel/mate-calc/help'
```

**Comment by lukefromdc** [comment]
I've never done release tarballs, as I recall it was some kind of issue with files being included that should not be, but I really don't know this part of the job very well.

**Comment by raveit65** [comment]
@rbuj  I am using also f30 daily.

@yetist 
Can you reproduce the concerns?

**Comment by rbuj** [comment]
@raveit65 I got the same warnings from another VM with F30.
```shell
sudo dnf upgrade -y
sudo dnf builddep mate-calc -y
sudo dnf install git -y
git clone https://github.com/mate-desktop/mate-calc.git
cd mate-calc
git checkout gettext
./autogen.sh --prefix=/usr
LANG=C ./makepot 
```

**Comment by yetist** [comment]
> @yetist
> Can you reproduce the concerns?

I can't reproduce this problem on Archlinux, and I'll try to do a test on F30.

**Comment by yetist** [comment]
@rbuj 

Please test it again, I removed a line that to set GETTEXTDATADIR variable.

**Comment by rbuj** [comment]
@yetist Now everything went well!
```shell
$ LANG=C ./makepot 
make: Entering directory '/home/robert/devel/mate-calc/po'
make mate-calc.pot-update
make[1]: Entering directory '/home/robert/devel/mate-calc/po'
sed -e '/^#/d' remove-potcdate.sin > t-remove-potcdate.sed
mv t-remove-potcdate.sed remove-potcdate.sed
package_gnu=""; \
test -n "$package_gnu" || { \
  if { if (LC_ALL=C find --version) 2>/dev/null | grep GNU >/dev/null; then \
	 LC_ALL=C find -L .. -maxdepth 1 -type f \
		       -size -10000000c -exec grep 'GNU mate-calc' \
		       /dev/null '{}' ';' 2>/dev/null; \
       else \
	 LC_ALL=C grep 'GNU mate-calc' ../* 2>/dev/null; \
       fi; \
     } | grep -v 'libtool:' >/dev/null; then \
     package_gnu=yes; \
   else \
     package_gnu=no; \
   fi; \
}; \
if test "$package_gnu" = "yes"; then \
  package_prefix='GNU '; \
else \
  package_prefix=''; \
fi; \
if test -n '' || test 'http://mate-desktop.org' = '@'PACKAGE_BUGREPORT'@'; then \
  msgid_bugs_address=''; \
else \
  msgid_bugs_address='http://mate-desktop.org'; \
fi; \
case `/usr/bin/xgettext --version | sed 1q | sed -e 's,^[^0-9]*,,'` in \
  '' | 0.[0-9] | 0.[0-9].* | 0.1[0-5] | 0.1[0-5].* | 0.16 | 0.16.[0-1]*) \
    /usr/bin/xgettext --default-domain=mate-calc --directory=.. \
      --add-comments=TRANSLATORS: --from-code=UTF-8 --keyword=_ --keyword=N_ --keyword=C_:1c,2 --keyword=NC_:1c,2 --keyword=g_dngettext:2,3 --add-comments  \
      --files-from=./POTFILES.in \
      --copyright-holder='MATE Desktop Environment team' \
      --msgid-bugs-address="$msgid_bugs_address" \
    ;; \
  *) \
    /usr/bin/xgettext --default-domain=mate-calc --directory=.. \
      --add-comments=TRANSLATORS: --from-code=UTF-8 --keyword=_ --keyword=N_ --keyword=C_:1c,2 --keyword=NC_:1c,2 --keyword=g_dngettext:2,3 --add-comments  \
      --files-from=./POTFILES.in \
      --copyright-holder='MATE Desktop Environment team' \
      --package-name="${package_prefix}mate-calc" \
      --package-version='1.23.0' \
      --msgid-bugs-address="$msgid_bugs_address" \
    ;; \
esac
test ! -f mate-calc.po || { \
  if test -f ./mate-calc.pot-header; then \
    sed -e '1,/^#$/d' < mate-calc.po > mate-calc.1po && \
    cat ./mate-calc.pot-header mate-calc.1po > mate-calc.po; \
    rm -f mate-calc.1po; \
  fi; \
  if test -f ./mate-calc.pot; then \
    sed -f remove-potcdate.sed < ./mate-calc.pot > mate-calc.1po && \
    sed -f remove-potcdate.sed < mate-calc.po > mate-calc.2po && \
    if cmp mate-calc.1po mate-calc.2po >/dev/null 2>&1; then \
      rm -f mate-calc.1po mate-calc.2po mate-calc.po; \
    else \
      rm -f mate-calc.1po mate-calc.2po ./mate-calc.pot && \
      mv mate-calc.po ./mate-calc.pot; \
    fi; \
  else \
    mv mate-calc.po ./mate-calc.pot; \
  fi; \
}
make[1]: Leaving directory '/home/robert/devel/mate-calc/po'
make: Leaving directory '/home/robert/devel/mate-calc/po'
make: Entering directory '/home/robert/devel/mate-calc/help'
  GEN      mate-calc.pot
make: Leaving directory '/home/robert/dev
```

**Comment by raveit65** [comment]
I  only squashed 4 commits into 2.

**Comment by raveit65** [comment]
@yetist 
I noticed more unknown and weird files (scripts ?) in /po folder if i am using `make dist` or `make distcheck` to create 1.23.0 tarball.
```
[rave@mother mate-calc-dist]$ cat mate-calc-1.23.0/po/boldquot.sed 
s/"\([^"]*\)"/“\1”/g
s/`\([^`']*\)'/‘\1’/g
s/ '\([^`']*\)' / ‘\1’ /g
s/ '\([^`']*\)'$/ ‘\1’/g
s/^'\([^`']*\)' /‘\1’ /g
s/“”/""/g
s/“/“/g
s/”/”/g
s/‘/‘/g
s/’/’/g
```
```
[rave@mother mate-calc-dist]$ cat mate-calc-1.23.0/po/en@boldquot.header 
# All this catalog "translates" are quotation characters.
# The msgids must be ASCII and therefore cannot contain real quotation
# characters, only substitutes like grave accent (0x60), apostrophe (0x27)
# and double quote (0x22). These substitutes look strange; see
# http://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html
#
# This catalog translates grave accent (0x60) and apostrophe (0x27) to
# left single quotation mark (U+2018) and right single quotation mark (U+2019).
# It also translates pairs of apostrophe (0x27) to
# left single quotation mark (U+2018) and right single quotation mark (U+2019)
# and pairs of quotation mark (0x22) to
# left double quotation mark (U+201C) and right double quotation mark (U+201D).
#
# When output to an UTF-8 terminal, the quotation characters appear perfectly.
# When output to an ISO-8859-1 terminal, the single quotation marks are
# transliterated to apostrophes (by iconv in glibc 2.2 or newer) or to
# grave/acute accent (by libiconv), and the double quotation marks are
# transliterated to 0x22.
# When output to an ASCII terminal, the single quotation marks are
# transliterated to apostrophes, and the double quotation marks are
# transliterated to 0x22.
#
# This catalog furthermore displays the text between the quotation marks in
# bold face, assuming the VT100/XTerm escape sequences.
#
```
```
[rave@mother mate-calc-dist]$ cat mate-calc-1.23.0/po/en@quot.header 
# All this catalog "translates" are quotation characters.
# The msgids must be ASCII and therefore cannot contain real quotation
# characters, only substitutes like grave accent (0x60), apostrophe (0x27)
# and double quote (0x22). These substitutes look strange; see
# http://www.cl.cam.ac.uk/~mgk25/ucs/quotes.html
#
# This catalog translates grave accent (0x60) and apostrophe (0x27) to
# left single quotation mark (U+2018) and right single quotation mark (U+2019).
# It also translates pairs of apostrophe (0x27) to
# left single quotation mark (U+2018) and right single quotation mark (U+2019)
# and pairs of quotation mark (0x22) to
# left double quotation mark (U+201C) and right double quotation mark (U+201D).
#
# When output to an UTF-8 terminal, the quotation characters appear perfectly.
# When output to an ISO-8859-1 terminal, the single quotation marks are
# transliterated to apostrophes (by iconv in glibc 2.2 or newer) or to
# grave/acute accent (by libiconv), and the double quotation marks are
# transliterated to 0x22.
# When output to an ASCII terminal, the single quotation marks are
# transliterated to apostrophes, and the double quotation marks are
# transliterated to 0x22.
#
```
```
[rave@mother mate-calc-dist]$ cat mate-calc-1.23.0/po/insert-header.sin 
# Sed script that inserts the file called HEADER before the header entry.
#
# At each occurrence of a line starting with "msgid ", we execute the following
# commands. At the first occurrence, insert the file. At the following
# occurrences, do nothing. The distinction between the first and the following
# occurrences is achieved by looking at the hold space.
/^msgid /{
x
# Test if the hold space is empty.
s/m/m/
ta
# Yes it was empty. First occurrence. Read the file.
r HEADER
# Output the file's contents by reading the next line. But don't lose the
# current line while doing this.
g
N
bb
:a
# The hold space was nonempty. Following occurrences. Do nothing.
x
:b
}
```
```
[rave@mother mate-calc-dist]$ cat mate-calc-1.23.0/po/remove-potcdate.sin 
# Sed script that remove the POT-Creation-Date line in the header entry
# from a POT file.
#
# The distinction between the first and the following occurrences of the
# pattern is achieved by looking at the hold space.
/^"POT-Creation-Date: .*"$/{
x
# Test if the hold space is empty.
s/P/P/
ta
# Yes it was empty. First occurrence. Remove the line.
g
d
bb
:a
# The hold space was nonempty. Following occurrences. Do nothing.
x
:b
}
```
```
[rave@mother mate-calc-dist]$ cat mate-calc-1.23.0/po/Rules-quot 
# This file, Rules-quot, can be copied and used freely without restrictions.
# Special Makefile rules for English message catalogs with quotation marks.

DISTFILES.common.extra1 = quot.sed boldquot.sed en@quot.header en@boldquot.header insert-header.sin Rules-quot

.SUFFIXES: .insert-header .po-update-en

en@quot.po-create:
	$(MAKE) en@quot.po-update
en@boldquot.po-create:
	$(MAKE) en@boldquot.po-update

en@quot.po-update: en@quot.po-update-en
en@boldquot.po-update: en@boldquot.po-update-en

.insert-header.po-update-en:
	@lang=`echo $@ | sed -e 's/\.po-update-en$$//'`; \
	if test "$(PACKAGE)" = "gettext-tools" && test "$(CROSS_COMPILING)" != "yes"; then PATH=`pwd`/../src:$$PATH; GETTEXTLIBDIR=`cd $(top_srcdir)/src && pwd`; export GETTEXTLIBDIR; fi; \
	tmpdir=`pwd`; \
	echo "$$lang:"; \
	ll=`echo $$lang | sed -e 's/@.*//'`; \
	LC_ALL=C; export LC_ALL; \
	cd $(srcdir); \
	if $(MSGINIT) $(MSGINIT_OPTIONS) -i $(DOMAIN).pot --no-translator -l $$lang -o - 2>/dev/null \
	   | $(SED) -f $$tmpdir/$$lang.insert-header | $(MSGCONV) -t UTF-8 | \
	   { case `$(MSGFILTER) --version | sed 1q | sed -e 's,^[^0-9]*,,'` in \
	     '' | 0.[0-9] | 0.[0-9].* | 0.1[0-8] | 0.1[0-8].*) \
	       $(MSGFILTER) $(SED) -f `echo $$lang | sed -e 's/.*@//'`.sed \
	       ;; \
	     *) \
	       $(MSGFILTER) `echo $$lang | sed -e 's/.*@//'` \
	       ;; \
	     esac } 2>/dev/null > $$tmpdir/$$lang.new.po \
	     ; then \
	  if cmp $$lang.po $$tmpdir/$$lang.new.po >/dev/null 2>&1; then \
	    rm -f $$tmpdir/$$lang.new.po; \
	  else \
	    if mv -f $$tmpdir/$$lang.new.po $$lang.po; then \
	      :; \
	    else \
	      echo "creation of $$lang.po failed: cannot move $$tmpdir/$$lang.new.po to $$lang.po" 1>&2; \
	      exit 1; \
	    fi; \
	  fi; \
	else \
	  echo "creation of $$lang.po failed!" 1>&2; \
	  rm -f $$tmpdir/$$lang.new.po; \
	fi

en@quot.insert-header: insert-header.sin
	sed -e '/^#/d' -e 's/HEADER/en@quot.header/g' $(srcdir)/insert-header.sin > en@quot.insert-header

en@boldquot.insert-header: insert-header.sin
	sed -e '/^#/d' -e 's/HEADER/en@boldquot.header/g' $(srcdir)/insert-header.sin > en@boldquot.insert-header

mostlyclean: mostlyclean-quot
mostlyclean-quot:
	rm -f *.insert-header
```
For what they are good for?
And do we really need them in tarballs?

**Comment by raveit65** [comment]
i forgot, the Makevars file is in tarball too .

**Comment by raveit65** [comment]
And i think we should exclude the mate-calc.pot file from tarball, or not?

**Comment by raveit65** [comment]
POTFILES.skip is missing :/

**Comment by yetist** [comment]
@raveit65 

These files are provided and needed by the new gettext.
https://www.gnu.org/software/gettext/manual/html_node/Adjusting-Files.html#Adjusting-Files
https://www.gnu.org/software/gettext/manual/html_node/po_002fRules_002d_002a.html#po_002fRules_002d_002a

**Comment by raveit65** [comment]
@yetist 
Ok, compilation from tarball without those new files will fail.
But POTFILES.skip is missing which have an entry and mate-calc.pot seems needless in tarball.

**Comment by raveit65** [comment]
And i have a feeling that we need the .gmo files in tarballs.
Installation from tarball without .gmo files, created with `autogen.sh && sed -i 's/$(POFILES) $(GMOFILES) \\/$(POFILES) \\/' po/Makefile.in.in && make && make dist`

```
rave@mother mate-calc-1.23.0]$ sudo make install
Making install in po
make[1]: Entering directory '/media/Data-2/Programme/Linux/Mate-Desktop/git-version/github-matedesktop/mate-calc-dist/mate-calc-1.23.0/po'
/usr/bin/install: cannot stat './af.gmo': No such file or directory
installing ./af.gmo as /usr/local/share/locale/af/LC_MESSAGES/mate-calc.mo
/usr/bin/install: cannot stat './am.gmo': No such file or directory
installing ./am.gmo as /usr/local/share/locale/am/LC_MESSAGES/mate-calc.mo

etc....
```
I need to check that with other new tarballs created by travis.

**Comment by raveit65** [comment]
@yetist 
I think it was a bad idea from me to remove the .gmo files from tarballs. Looks like that they are needed if using `gettext`
With marco-1.23.1 locale will be installed with `sudo make install`, but not with this test tarball (1.23.2) https://github.com/raveit65/marco/releases/tag/v1.23.2
I tested installation to /usr/local dir.
Can you confirm my result?

**Comment by yetist** [comment]
Yes, I confirm that can't install mo files into system.

```
[yetist mate-calc-1.23.0 (master *%)]$ DESTDIR=/tmp/inst make install
Making install in po
make[1]: 进入目录“/home/yetist/checkout/03-mate-desktop/mate-calc/mate-calc-1.23.0/po”
/usr/bin/install: 无法获取'./af.gmo' 的文件状态(stat): 没有那个文件或目录
installing ./af.gmo as /tmp/inst/usr/share/locale/af/LC_MESSAGES/mate-calc.mo
/usr/bin/install: 无法获取'./am.gmo' 的文件状态(stat): 没有那个文件或目录
installing ./am.gmo as /tmp/inst/usr/share/locale/am/LC_MESSAGES/mate-calc.mo
/usr/bin/install: 无法获取'./ar.gmo' 的文件状态(stat): 没有那个文件或目录
```

**Comment by yetist** [comment]
> @yetist
> Ok, compilation from tarball without those new files will fail.
> But POTFILES.skip is missing which have an entry and mate-calc.pot seems needless in tarball.

I think the `POTFILES.skip` is no longer used, you can run `grep POTFILES po/*` to confirm, and `POTFILES.skip` not listed here: https://www.gnu.org/software/gettext/manual/html_node/Adjusting-Files.html#Adjusting-Files.

About `po/mate-calc.pot`, I think we can change `.tx/config`, let `source_file = po/mate-calc.pot` and remove $top_srcdir/mate-calc.pot.

**Comment by raveit65** [comment]
> About `po/mate-calc.pot`, I think we can change `.tx/config`, let `source_file = po/mate-calc.pot` and remove $top_srcdir/mate-calc.pot.

We can, but this doesn't solve the problem that we ship `po/mate-calc.pot` in tarball , which isn't needed for installation and using locale.
The old `$top_srcdir/mate-calc.pot` was never shipped in tarball.

Well, it's only a minimal issue, no need to solve it when there isn't a simple solution.

**Comment by raveit65** [comment]
Makefile.in.in in tarball with
```
DISTFILES = $(DISTFILES.common) Makevars POTFILES.in \
$(POFILES) \
$(DISTFILES.extra1) $(DISTFILES.extra2) $(DISTFILES.extra3)
```
can't create the .gmo files during compiling, in result installation of .mo files doesn`t work.
@yetist 
Do you agree with reverting https://github.com/mate-desktop/mate-calc/commit/87d647ad3be67c033dbb6aa80cfcdd4cbce3a42d
? Or do you have another idea?
I will do that in other repos too.

**Comment by yetist** [comment]
I agree, please do.

**Pull request merged**
