### PR TITLE
Unit tests: pi constant, ln (e^iπ)

### PR DESCRIPTION
**Pull request by rbuj**

### CODE REVIEW

**Comment by sc0w** [comment]
my tests:

1) I reverted locally https://github.com/mate-desktop/mate-calc/commit/b0e4fe242b2b7b0a980d163bbf294f588b084091

2) I built this PR without the mentioned commit.

3) I expected the build fails, but the build is frozen:

**Comment by rbuj** [comment]
@sc0w 
It's `./src/test-mp-equation`

**Comment by sc0w** [comment]
I think when I see `PASS: test-tmp` the tests `test-tmp` was ok

and I see the prompt frozen because `test-mp-equation` is frozen

this PR without https://github.com/mate-desktop/mate-calc/commit/b0e4fe242b2b7b0a980d163bbf294f588b084091 :

```
$ ./src/test-mp
base=10000
MPNumber(0) -> {sign=0 exponent=0 fraction=0,...}
MPNumber(1) -> {sign=1 exponent=1 fraction=1,...}
MPNumber(-1) -> {sign=-1 exponent=1 fraction=1,...}
MPNumber(2) -> {sign=1 exponent=1 fraction=2,...}
MPNumber(9999) -> {sign=1 exponent=1 fraction=9999,...}
MPNumber(10000) -> {sign=1 exponent=2 fraction=1,...}
MPNumber(10001) -> {sign=1 exponent=2 fraction=1,1,...}
MPNumber(2147483647) -> {sign=1 exponent=3 fraction=21,4748,3647,...}
MPNumber(0) -> {sign=0 exponent=0 fraction=0,...}
MPNumber(1) -> {sign=1 exponent=1 fraction=1,...}
MPNumber(-1) -> {sign=-1 exponent=1 fraction=1,...}
MPNumber(16383) -> {sign=1 exponent=2 fraction=1,6383,...}
MPNumber(16384) -> {sign=1 exponent=2 fraction=1,6384,...}
MPNumber(16385) -> {sign=1 exponent=2 fraction=1,6385,...}
MPNumber(268435456) -> {sign=1 exponent=3 fraction=2,6843,5456,...}
MPNumber(0.1) -> {sign=1 exponent=0 fraction=1000,...}
MPNumber(0.5) -> {sign=1 exponent=0 fraction=5000,...}
MPNumber(0.25) -> {sign=1 exponent=0 fraction=2500,...}
MPNumber(0.125) -> {sign=1 exponent=0 fraction=1250,...}
MPNumber(0.0625) -> {sign=1 exponent=0 fraction=625,...}
MPNumber(0.00006103515625) -> {sign=1 exponent=-1 fraction=6103,5156,2500,...}
MPNumber(0.000030517578125) -> {sign=1 exponent=-1 fraction=3051,7578,1250,...}
MPNumber(1.00006103515625) -> {sign=1 exponent=1 fraction=1,0,6103,5156,2500,...}
MPNumber(16384.00006103515625) -> {sign=1 exponent=2 fraction=1,6384,0,6103,5156,2500,...}
Passed all 63 tests
```

`$ ./src/test-mp-equation` shows nothing, is frozen, never ends

maybe we can revert here https://github.com/mate-desktop/mate-calc/commit/b0e4fe242b2b7b0a980d163bbf294f588b084091 temporarily to see whan happen in logs?

**Comment by rbuj** [comment]
You can set a timeout for `make check`:
```
$ timeout 30s make check
```

**Comment by sc0w** [comment]
well, maybe this is the expected, because the gui without https://github.com/mate-desktop/mate-calc/commit/b0e4fe242b2b7b0a980d163bbf294f588b084091 was frozen too, calculating that value

**Pull request merged**
