### PR TITLE
mate-calc.desktop.in: Add missing Keywords.

### PR DESCRIPTION
**Pull request by flexiondotorg**
Taken from a downstream Debian patch.

### CODE REVIEW

**Comment by rbuj** [comment]
The multiple values should be separated by a semicolon and the value of the key may be optionally terminated by a semicolon. Trailing empty strings must always be terminated with a semicolon.
```
Keywords=calculator;MATE;scientifc;arithmetic;financial;calculations;
```
https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

**Comment by flexiondotorg** [comment]
@rbuj Gosh, how did I make that mistake? Thanks, I'll correct it.

**Comment by rbuj** [comment]
mate-ccalc was migrated to gettext https://github.com/mate-desktop/mate-calc/commit/9ee7e00057ce3d7b4dc6cf22074fc54bf8f48b3e

gettext do not requires adding an underscore at the beginning for marking the translations.

**Comment by flexiondotorg** [comment]
Dropped the `_` prefix for `Keywords=`.

**Comment by monsta** [comment]
Hmm, these keywords don't appear in the potfile if I run makepot...

**Pull request merged**
