### PR TITLE
replace deprecated gtk_menu_popup

### PR DESCRIPTION
**Pull request by raveit65**
Please test.
Honestly i don't know which menu is affected exactly.
Some buttons have a left-click menu but i don't see the expected different.

### CODE REVIEW

**Comment by sc0w** [comment]
This is the affected popup menu:

image823

screenshot at 2018-05-25 17-45-40

I will test it later

**Comment by raveit65** [comment]
great, looks like i've broke it...

**Comment by sc0w** [comment]
Without the PR:

screenshot at 2018-05-25 17-45-40

With the PR:

screenshot at 2018-05-25 18-20-44

Looks better under the widget, and it works every time I clicked

**Comment by raveit65** [comment]
Yeah, i tested it again and it is working.
And thanks for testing.

**Comment by lukefromdc** [comment]
Didn't get any issues from NULL(default) on the event either

**Comment by lukefromdc** [comment]
Default "merge" button never gives ''ff-only" and replaces the commit message. Apparently only "rebase and merge" works when not merging from the command line. Unfortunately only way to fix this one committed would involve a force-push, which would break any local repo updated after the offending merge and prior to the force-push

**Pull request merged**
