### PR TITLE
initial support for meson

### PR DESCRIPTION
**Pull request by bruci**

### CODE REVIEW

**Comment by raveit65** [comment]
I suggest to open an a report first where this can be discussed with all needed infos why this is needed.

**Comment by sc0w** [comment]
the meson build system:

http://mesonbuild.com

(I have no idea about that)

**Comment by monsta** [comment]
Which problem does it solve?

**Comment by jhasse** [comment]
Here are some points why Meson is an improvement over Autotools: https://in.waw.pl/~zbyszek/blog/systemd-meson.html

**Comment by raveit65** [comment]
Does this commit remove build with autotools?
We have a discussion about meson in another PR https://github.com/mate-desktop/mate-calc/pull/65
And we need to support both autotools and meson for several reasons.
Place for general discussion about integration of meson build system is here.
https://github.com/orgs/mate-desktop/teams/core-team/discussions/11

**Comment by bruci** [comment]
OK. I'll reformat it.

How exactly would you like it?

**Comment by raveit65** [comment]
No tabs and Indents should be correct.
Simply take a lock how you commit looks in browser ;)
adding .diff to link of PR.
https://github.com/mate-desktop/mate-calc/pull/37.diff

**Comment by yetist** [comment]
@bruci 

Can you continue to finish this PR? #111 completed the migration from intltools to gettext, which should help.

**Comment by yetist** [comment]
When building with ninja, I got the warning:
```
[7/57] Compiling C object 'src/25a6634@@mate-calc@exe/mate-calc.c.o'.                                    
In file included from ../src/utility.h:5,     
                 from ../src/mate-calc.c:22:                                                             
./config.h:12: warning: "G_LOG_DOMAIN" redefined
 #define G_LOG_DOMAIN "org.mate.calc"
                                                    
In file included from /usr/include/glib-2.0/glib.h:62,
                 from /usr/include/glib-2.0/glib/gi18n.h:21,
                 from ../src/mate-calc.c:16:
/usr/include/glib-2.0/glib/gmessages.h:295: note: this is the location of the previous definition
 #define G_LOG_DOMAIN    ((gchar*) 0)
```

**Comment by raveit65** [comment]
Migration from intltools into gettext is now merge in master.
You should rebase against master to get this changes in your PR.

**Comment by bruci** [comment]
Please test again

**Comment by lukefromdc** [comment]
I now get these two errors in terminal and the install still slows down, but the install does in fact finish and the installed .deb package works. All 112 directories do in fact show up:

```
msgfmt: error while opening "/home/luke/Desktop/Development/MATE_Development_Work/mate-calc_1.23.0+meson20190612/help/C/C.po" for reading: No such file or directory
Error: cannot open mo file /home/luke/Desktop/Development/MATE_Development_Work/mate-calc_1.23.0+meson20190612/build/help/C/C.gmo
```

These are followed by lines like:

`Installing /home/luke/Desktop/Development/MATE_Development_Work/mate-calc_1.23.0+meson20190612/build/help/af/absolute.page to /home/luke/Desktop/Development/MATE_Development_Work/mate-calc_1.22.0+meson-1luke1_amd64/usr/share/help/af/mate-calc/absolute.page`

Help works fine in english but I can't test other languages as I only understand one language and have other locales purged.

**Comment by bruci** [comment]
should be fixed now. I'll look into this slowdown too.

**Comment by raveit65** [comment]
Adding a LINGUAS file to help dir is really a step back to me, because you need to add a new language  by hand after a pull from transifex server.
With using autotools build system this is handled in make file.
https://github.com/mate-desktop/mate-calc/blob/master/help/Makefile.am#L34
```
# Add linguas to be ignored, e.g. IGNORE_HELP_LINGUAS = ca de es fr
IGNORE_HELP_LINGUAS =
HELP_LINGUAS = $(if $(IGNORE_HELP_LINGUAS), \
	$(filter-out $(IGNORE_HELP_LINGUAS),$(subst /,,$(dir $(wildcard */*.po)))), \
	$(subst /,,$(dir $(wildcard */*.po))) )
```
Any chance to do something similar for meson build?

**Comment by raveit65** [comment]
Any NEWS ?

@rbuj 
Do you see a chance to avoid to add a LINGUAS file to help dir?
I mean we will run into this problem with other repos too.

**Comment by raveit65** [comment]
@bruci 
We have open questions
https://github.com/mate-desktop/mate-calc/pull/37#issuecomment-503000088

**Comment by lukefromdc** [comment]
Any progress on this?

**Comment by raveit65** [comment]
We have conflicts.....

**Comment by lukefromdc** [comment]
Does anyone plan to fix the conflicts in this?

**Comment by raveit65** [comment]
@bruci 
I am fine with using a Linguas file. Can you please update PR to fix conflicts?
Than i will start with a final test.

**Comment by zhuyaliang** [comment]
@raveit65 If necessary, I can continue this pr

**Comment by raveit65** [comment]
@zhuyaliang 
That would be nice....

**Comment by raveit65** [comment]
Already done https://github.com/mate-desktop/mate-calc/commit/8dca108a6a4bed0b3411e41cb04b143c71036b67

**Pull request closed without merging**
