### PR TITLE
avoid deprecated GtkStock

### PR DESCRIPTION
**Pull request by sc0w**
The expected with this PR: the same icons like before

### CODE REVIEW

**Comment by raveit65** [comment]
Translations affected?

**Comment by raveit65** [comment]
@sc0w 
If you say translations aren't affected than we should merge it for 1.20 release.
Better as seeing those warnings 1 year again in compilation :-)

**Comment by sc0w** [comment]
I use the english as default in my system

with

`$ env LANG=es_ES.UTF-8 mate-calc`

apparently I see all the words translated

**Comment by raveit65** [comment]
OK, let's merge.
I will update tarball at pre-release.

**Comment by sc0w** [comment]
merged: https://github.com/mate-desktop/mate-calc/commit/719cc6f6ba0f0d06b875746c99cf1a51031c35f1

**Pull request merged**
