### PR TITLE
tx: update resource

### PR DESCRIPTION
**Pull request by mbkma**

### CODE REVIEW

**Review by raveit65 — APPROVED** [review]
LGTM,
i think you can do such changes without a PR.
I never asked for it......

**Comment by raveit65** [comment]
Automatic update works like this at transifex.
Screenshot 2022-10-28 at 20-36-39 The MATE Desktop Environment translation project on Transifex

**Comment by mbkma** [comment]
I can not see this page at transifex. Can you maybe add me to administrators there?

**Comment by raveit65** [comment]
Invitation is send. Here the current setup is fine.
Only a new stable branch you need to add new paths in this dialog.
Normally we use paths of master and current stable branch.
I deleted the sources of older branches after a new release to reduce workload of translators.

**Pull request merged**
